"""Tests for IPD-C: `pubrun bench` (friendly runner + Slurm submit) and result redaction.

Focus: the SAFETY-critical bits — redaction actually removes PII (deep scan) while keeping
analysis fields, `--no-redact` keeps detail, Slurm is detected but NEVER auto-submitted
without confirmation, and harness resolution fails cleanly for a non-checkout install.
"""
import os
import sys
import json
import getpass
import subprocess
import importlib.util
from pathlib import Path

import pytest

PYTHON = sys.executable
_REPO = Path(__file__).resolve().parents[1]


def _load_harness():
    """Import benchmarks/harness.py directly (it is not on the package path)."""
    path = _REPO / "benchmarks" / "harness.py"
    spec = importlib.util.spec_from_file_location("_bench_harness", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def run_pubrun(*args, cwd=None, env=None, stdin=None, timeout=60):
    e = dict(os.environ)
    if env:
        e.update(env)
    return subprocess.run([PYTHON, "-m", "pubrun"] + list(args), capture_output=True,
                          text=True, cwd=cwd or os.getcwd(), timeout=timeout, env=e, input=stdin)


# --------------------------------------------------------------------------- redaction

class TestRedaction:

    @pytest.fixture
    def sample(self):
        home = os.path.expanduser("~")
        user = getpass.getuser()
        return {
            "machine": {
                "host": {"hostname": "secret-node-01"},
                "python": {
                    "executable": f"{home}/venv/bin/python",
                    "prefix": f"{home}/venv",
                    "sys_path": [f"{home}/project/src", "/usr/lib/python3"],
                },
                "filesystem": {
                    "tmpdir": {"path": "/tmp", "mount_point": "/tmp", "fstype": "tmpfs"},
                    "install": {"path": f"{home}/project", "fstype": "nfs4", "is_network": True},
                },
                "slurm": {"partition": "compute", "node": "cn-9"},
                "hardware": {"cpu": {"model": "Test CPU 9000", "logical_cores": 8}},
            },
            "note": f"generated by {user} under {home}/project",  # un-enumerated PII field
            "pubrun_version": "1.4.0",
        }

    def test_redaction_removes_all_pii(self, sample):
        h = _load_harness()
        red = h.redact_result(sample)
        blob = json.dumps(red)
        assert getpass.getuser() not in blob
        assert os.path.expanduser("~") not in blob
        assert "secret-node-01" not in blob
        assert red["machine"]["host"]["hostname"] == "<redacted>"
        # un-enumerated field scrubbed by the belt-and-suspenders pass
        assert getpass.getuser() not in red["note"]

    def test_redaction_preserves_analysis_fields(self, sample):
        h = _load_harness()
        red = h.redact_result(sample)
        assert red["pubrun_version"] == "1.4.0"
        assert red["machine"]["hardware"]["cpu"]["model"] == "Test CPU 9000"
        assert red["machine"]["hardware"]["cpu"]["logical_cores"] == 8
        assert red["machine"]["slurm"]["partition"] == "compute"
        assert red["machine"]["filesystem"]["tmpdir"]["fstype"] == "tmpfs"
        assert red["machine"]["filesystem"]["install"]["is_network"] is True

    def test_redaction_does_not_mutate_input(self, sample):
        h = _load_harness()
        original = json.dumps(sample)
        h.redact_result(sample)
        assert json.dumps(sample) == original  # deep-copied, input untouched


# ----------------------------------------------------------------- harness resolution

class TestHarnessResolution:

    def test_find_harness_in_checkout(self):
        from pubrun.__main__ import _find_bench_harness
        found = _find_bench_harness()
        assert found is not None
        assert found.name == "harness.py"

    def test_bench_errors_without_checkout(self, tmp_path, monkeypatch):
        """When no harness can be found, bench must error clearly (not crash)."""
        import pubrun.__main__ as m
        monkeypatch.setattr(m, "_find_bench_harness", lambda: None)
        with pytest.raises(SystemExit) as ei:
            m._run_bench(None, None, False, True, False, False, False, False)
        assert ei.value.code == 1


# --------------------------------------------------------------------- Slurm / submit

class TestSlurmSafety:

    def test_slurm_detected_but_not_submitted_without_confirmation(self, monkeypatch, capsys):
        """Slurm present, interactive 'no' answer => must NOT submit."""
        import pubrun.__main__ as m
        monkeypatch.setattr(m, "_slurm_available", lambda: True)
        monkeypatch.setattr(m, "_on_compute_node", lambda: False)
        monkeypatch.setattr("builtins.input", lambda *a: "n")
        called = {"ran": False}
        import subprocess as sp
        def _boom(*a, **k):
            called["ran"] = True
            raise AssertionError("must not submit without confirmation")
        monkeypatch.setattr(sp, "run", _boom)
        # local=False, submit=False, yes=False -> would offer submit, user says no
        m._run_bench(None, None, False, False, False, False, False, False)
        assert called["ran"] is False

    def test_slurm_detection_reads_env(self, monkeypatch):
        from pubrun.__main__ import _slurm_available, _on_compute_node
        monkeypatch.setenv("SLURM_JOB_ID", "12345")
        assert _slurm_available() is True
        assert _on_compute_node() is True
        monkeypatch.delenv("SLURM_JOB_ID", raising=False)


# ------------------------------------------------------------------------- CLI smoke

class TestBenchCLI:

    def test_bench_help(self):
        res = run_pubrun("bench", "--help")
        assert res.returncode == 0
        assert "Examples:" in res.stdout

    def test_bench_quick_local_json(self, tmp_path):
        """A minimal local run writes results + a redacted copy (verified clean).

        Kept as light as possible (1 iteration, 1 pass) but still launches many fresh
        Python subprocesses, so it is a slower end-to-end test (generous timeout).
        """
        res = run_pubrun("bench", "--iterations", "1", "--passes", "1", "--local", "--json",
                         cwd=str(_REPO), timeout=180)
        assert res.returncode == 0, res.stderr
        data = json.loads(res.stdout)
        results = Path(data["results"])
        redacted = Path(data["redacted"])
        try:
            assert results.exists() and redacted.exists()
            blob = redacted.read_text()
            assert getpass.getuser() not in blob
            assert os.path.expanduser("~") not in blob
        finally:
            results.unlink(missing_ok=True)
            redacted.unlink(missing_ok=True)
