"""Tests for IPD-C: `pubrun bench` (friendly runner + Slurm submit) and result redaction.

Focus: the SAFETY-critical bits — redaction actually removes PII (deep scan) while keeping
analysis fields, `--no-redact` keeps detail, Slurm is detected but NEVER auto-submitted
without confirmation, and harness resolution fails cleanly for a non-checkout install.
"""
import os
import sys
import json
import getpass
import subprocess
import importlib.util
from pathlib import Path

import pytest

PYTHON = sys.executable
_REPO = Path(__file__).resolve().parents[1]


def _load_harness():
    """Import benchmarks/harness.py directly (it is not on the package path)."""
    path = _REPO / "benchmarks" / "harness.py"
    spec = importlib.util.spec_from_file_location("_bench_harness", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def run_pubrun(*args, cwd=None, env=None, stdin=None, timeout=60):
    e = dict(os.environ)
    if env:
        e.update(env)
    return subprocess.run([PYTHON, "-m", "pubrun"] + list(args), capture_output=True,
                          text=True, cwd=cwd or os.getcwd(), timeout=timeout, env=e, input=stdin)


# --------------------------------------------------------------------------- redaction

class TestRedaction:

    @pytest.fixture
    def sample(self):
        home = os.path.expanduser("~")
        user = getpass.getuser()
        return {
            "machine": {
                "host": {"hostname": "secret-node-01"},
                "python": {
                    "executable": f"{home}/venv/bin/python",
                    "prefix": f"{home}/venv",
                    "sys_path": [f"{home}/project/src", "/usr/lib/python3"],
                },
                "filesystem": {
                    "tmpdir": {"path": "/tmp", "mount_point": "/tmp", "fstype": "tmpfs"},
                    "install": {"path": f"{home}/project", "fstype": "nfs4", "is_network": True},
                },
                "slurm": {"partition": "compute", "node": "cn-9"},
                "hardware": {"cpu": {"model": "Test CPU 9000", "logical_cores": 8}},
            },
            "note": f"generated by {user} under {home}/project",  # un-enumerated PII field
            "pubrun_version": "1.4.0",
        }

    def test_redaction_removes_all_pii(self, sample):
        h = _load_harness()
        red = h.redact_result(sample)
        blob = json.dumps(red)
        assert getpass.getuser() not in blob
        assert os.path.expanduser("~") not in blob
        assert "secret-node-01" not in blob
        assert red["machine"]["host"]["hostname"] == "<redacted>"
        # un-enumerated field scrubbed by the belt-and-suspenders pass
        assert getpass.getuser() not in red["note"]

    def test_redaction_preserves_analysis_fields(self, sample):
        h = _load_harness()
        red = h.redact_result(sample)
        assert red["pubrun_version"] == "1.4.0"
        assert red["machine"]["hardware"]["cpu"]["model"] == "Test CPU 9000"
        assert red["machine"]["hardware"]["cpu"]["logical_cores"] == 8
        assert red["machine"]["slurm"]["partition"] == "compute"
        assert red["machine"]["filesystem"]["tmpdir"]["fstype"] == "tmpfs"
        assert red["machine"]["filesystem"]["install"]["is_network"] is True

    def test_redaction_does_not_mutate_input(self, sample):
        h = _load_harness()
        original = json.dumps(sample)
        h.redact_result(sample)
        assert json.dumps(sample) == original  # deep-copied, input untouched

    def test_redaction_of_schema5_shape_removes_all_pii(self):
        """PR-005: after the schema/5 reshape, the key/needle-based redactor must still mask
        hostname/username/home-paths (a moved field must stay covered) and the deep scan
        must find zero PII needles in the redacted /5 result."""
        import re
        h = _load_harness()
        home = os.path.expanduser("~")
        user = getpass.getuser()
        result = {
            "schema": "pubrun-benchmark/5",
            "generated_utc": "2026-07-20T00:00:00+00:00",
            "generated_local": "2026-07-19T20:00:00-04:00",
            "machine": {
                "host": {"hostname": "secret-node-01"},
                "python": {"executable": f"{home}/venv/bin/python", "prefix": f"{home}/venv",
                           "sys_path": [f"{home}/src", "/usr/lib/python3"]},
                "filesystem": {"install": {"path": f"{home}/project", "fstype": "nfs4"}},
            },
            # scenario_defs still carries config, which could embed a path.
            "scenario_defs": {"s": {"group": "startup", "mode": "auto", "workload": "noop.py",
                                    "config": {"output": {"run_dir": f"{home}/runs"}}}},
            "pass_results": [{"pass": 1, "pass_env": {"note": f"ran by {user}"},
                              "timings": {"s": [0.1, 0.2]}, "failures": {"s": 0}}],
        }
        red = h.redact_result(result)
        blob = json.dumps(red)
        assert user not in blob
        assert home not in blob
        assert "secret-node-01" not in blob
        assert red["machine"]["host"]["hostname"] == "<redacted>"
        # config path masked (run_dir is an enumerated key), timings preserved.
        assert red["scenario_defs"]["s"]["config"]["output"]["run_dir"] == "<redacted>"
        assert red["pass_results"][0]["timings"]["s"] == [0.1, 0.2]


# ----------------------------------------------------------------- harness resolution

class TestHarnessResolution:

    def test_find_harness_in_checkout(self):
        from pubrun.__main__ import _find_bench_harness
        found = _find_bench_harness()
        assert found is not None
        assert found.name == "harness.py"

    def test_bench_errors_without_checkout(self, tmp_path, monkeypatch):
        """When no harness can be found, bench must error clearly (not crash)."""
        import pubrun.__main__ as m
        monkeypatch.setattr(m, "_find_bench_harness", lambda: None)
        with pytest.raises(SystemExit) as ei:
            m._run_bench(None, None, False, True, False, False, False, False)
        assert ei.value.code == 1


# --------------------------------------------------------------------- Slurm / submit

class TestSlurmSafety:

    def test_slurm_detected_but_not_submitted_without_confirmation(self, monkeypatch, capsys):
        """Slurm present, interactive 'no' answer => must NOT submit."""
        import pubrun.__main__ as m
        monkeypatch.setattr(m, "_slurm_available", lambda: True)
        monkeypatch.setattr(m, "_on_compute_node", lambda: False)
        monkeypatch.setattr("builtins.input", lambda *a: "n")
        called = {"ran": False}
        import subprocess as sp
        def _boom(*a, **k):
            called["ran"] = True
            raise AssertionError("must not submit without confirmation")
        monkeypatch.setattr(sp, "run", _boom)
        # local=False, submit=False, yes=False -> would offer submit, user says no
        m._run_bench(None, None, False, False, False, False, False, False)
        assert called["ran"] is False

    def test_slurm_detection_reads_env(self, monkeypatch):
        from pubrun.__main__ import _slurm_available, _on_compute_node
        monkeypatch.setenv("SLURM_JOB_ID", "12345")
        assert _slurm_available() is True
        assert _on_compute_node() is True
        monkeypatch.delenv("SLURM_JOB_ID", raising=False)


# ------------------------------------------------- IPD: HPC multi-scheduler (2026-07-07)

class TestSchedulerDetection:
    """Detection is env+PATH only, side-effect-free; PBS-vs-SGE qsub ambiguity handled."""

    def _m(self):
        import pubrun.__main__ as m
        return m

    def _no_tools(self, m, monkeypatch):
        # Neutralize PATH tools + env so each test controls exactly what is "present".
        import shutil
        monkeypatch.setattr(shutil, "which", lambda t: None)
        for v in ("SLURM_JOB_ID", "PBS_JOBID", "PBS_ENVIRONMENT", "PBS_O_HOST",
                  "LSB_JOBID", "SGE_ROOT", "SGE_O_HOST", "PE_HOSTFILE", "JOB_ID"):
            monkeypatch.delenv(v, raising=False)

    def test_pbs_detected_via_env(self, monkeypatch):
        m = self._m()
        self._no_tools(m, monkeypatch)
        monkeypatch.setenv("PBS_JOBID", "123.head")
        names = [d["name"] for d in m._detect_schedulers()]
        assert "pbs" in names

    def test_lsf_detected_via_env(self, monkeypatch):
        m = self._m()
        self._no_tools(m, monkeypatch)
        monkeypatch.setenv("LSB_JOBID", "999")
        names = [d["name"] for d in m._detect_schedulers()]
        assert "lsf" in names

    def test_sge_detected_via_markers(self, monkeypatch):
        import shutil
        m = self._m()
        self._no_tools(m, monkeypatch)
        monkeypatch.setenv("SGE_ROOT", "/opt/sge")
        monkeypatch.setattr(shutil, "which", lambda t: "/usr/bin/qsub" if t == "qsub" else None)
        names = [d["name"] for d in m._detect_schedulers()]
        assert "sge" in names

    def test_qsub_ambiguous_when_no_markers(self, monkeypatch):
        import shutil
        m = self._m()
        self._no_tools(m, monkeypatch)
        monkeypatch.setattr(shutil, "which", lambda t: "/usr/bin/qsub" if t == "qsub" else None)
        assert m._qsub_ambiguous() is True  # qsub present, neither PBS nor SGE markers

    def test_detection_makes_no_subprocess_call(self, monkeypatch):
        """Detection must be side-effect-free: env + which only, never a scheduler query."""
        import subprocess
        m = self._m()
        monkeypatch.setattr(subprocess, "run",
                            lambda *a, **k: (_ for _ in ()).throw(AssertionError("no subprocess in detection")))
        monkeypatch.setattr(subprocess, "check_output",
                            lambda *a, **k: (_ for _ in ()).throw(AssertionError("no subprocess in detection")))
        m._detect_schedulers()  # must not raise
        m._qsub_ambiguous()


class TestSchedulerSubmitSafety:
    """Never auto-submit for ANY scheduler; injection stays literal; scripts exist."""

    def _m(self):
        import pubrun.__main__ as m
        return m

    def test_pbs_detected_but_not_submitted_without_confirmation(self, monkeypatch):
        m = self._m()
        monkeypatch.setattr(m, "_detect_schedulers",
                            lambda: [{"name": "pbs", "submit_script": "submit_bench_pbs.sh",
                                      "on_compute_node": False}])
        monkeypatch.setattr("builtins.input", lambda *a: "n")
        import subprocess as sp
        monkeypatch.setattr(sp, "run",
                            lambda *a, **k: (_ for _ in ()).throw(AssertionError("must not submit on 'no'")))
        # auto scheduler, not local, not --submit/--yes: offers, user declines -> no submit.
        m._run_bench(None, None, False, False, False, False, False, False, scheduler="auto")

    def test_scheduler_local_forces_local_no_submit(self, monkeypatch, tmp_path):
        m = self._m()
        monkeypatch.setattr(m, "_detect_schedulers",
                            lambda: [{"name": "slurm", "submit_script": "submit_bench.sh",
                                      "on_compute_node": False}])
        import subprocess as sp
        # --scheduler local must never enter the submit branch (which would sp.run bash).
        calls = []
        real_run = sp.run
        monkeypatch.setattr(sp, "run", lambda *a, **k: calls.append(a) or real_run(*a, **k))
        # Point at a nonexistent harness so it errors out fast AFTER skipping submit.
        monkeypatch.setattr(m, "_find_bench_harness", lambda: None)
        try:
            m._run_bench(None, None, True, False, False, False, False, False, scheduler="local")
        except SystemExit:
            pass
        # No `bash submit_*.sh` call happened.
        assert not any(a and str(a[0][:2]) == "['bash'" for a in calls if a and isinstance(a[0], list))

    def test_new_submit_scripts_exist_and_quote_vars(self):
        for name in ("submit_bench_pbs.sh", "submit_bench_lsf.sh", "submit_bench_sge.sh"):
            p = _REPO / "benchmarks" / name
            assert p.is_file(), f"{name} missing"
            text = p.read_text()
            # argv-array options (no shell-string interpolation of user values).
            assert "QSUB_OPTS=(" in text or "BSUB_OPTS=(" in text
            # site-adaptation honesty note present.
            assert "STARTING POINT" in text


# ------------------------------------------------------------------------- CLI smoke

class TestBenchCLI:

    def test_bench_help(self):
        res = run_pubrun("bench", "--help")
        assert res.returncode == 0
        assert "Examples:" in res.stdout

    def test_bench_quick_local_json(self, tmp_path):
        """A minimal local run writes results + a redacted copy (verified clean).

        Kept as light as possible (1 iteration, 1 pass) but still launches many fresh
        Python subprocesses, so it is a slower end-to-end test (generous timeout).
        """
        res = run_pubrun("bench", "--iterations", "1", "--passes", "1", "--local", "--json",
                         cwd=str(_REPO), timeout=180)
        assert res.returncode == 0, res.stderr
        data = json.loads(res.stdout)
        results = Path(data["results"])
        redacted = Path(data["redacted"])
        try:
            assert results.exists() and redacted.exists()
            blob = redacted.read_text()
            assert getpass.getuser() not in blob
            assert os.path.expanduser("~") not in blob
        finally:
            results.unlink(missing_ok=True)
            redacted.unlink(missing_ok=True)


class TestIoBaselineScenarios:
    """IPD (2026-07-07): /dev/null + /dev/shm + tmpdir ground-truth I/O baselines."""

    def _scenarios(self):
        import importlib.util
        path = _REPO / "benchmarks" / "scenarios.py"
        spec = importlib.util.spec_from_file_location("_bench_scenarios", path)
        mod = importlib.util.module_from_spec(spec)
        # Register before exec so the @dataclass decorator can resolve cls.__module__
        # (Python 3.12+ dataclasses look up sys.modules[cls.__module__] during processing).
        sys.modules[spec.name] = mod
        spec.loader.exec_module(mod)
        return mod.all_scenarios()

    def test_io_baseline_scenarios_registered(self):
        names = {s.name for s in self._scenarios()}
        assert {"io-baseline-devnull", "io-baseline-devshm", "io-baseline-tmpdir"} <= names

    def test_devnull_targets_null_device(self):
        s = next(s for s in self._scenarios() if s.name == "io-baseline-devnull")
        assert s.env.get("PUBRUN_BENCH_IO_TARGET") in ("/dev/null", "NUL")
        assert s.group == "io_baseline"

    def test_devshm_skips_when_unavailable(self):
        s = next(s for s in self._scenarios() if s.name == "io-baseline-devshm")
        reason = s.skip_if() if s.skip_if else None
        # On Linux with /dev/shm writable -> not skipped; elsewhere -> a skip reason string.
        if sys.platform.startswith("linux") and os.path.isdir("/dev/shm") and os.access("/dev/shm", os.W_OK):
            assert reason is None
        else:
            assert isinstance(reason, str) and reason

    def test_io_sink_workload_null_and_tmpdir(self, tmp_path):
        """The io_sink workload handles both a null sink (write-only) and a dir target."""
        import importlib.util
        path = _REPO / "benchmarks" / "workloads" / "io_sink.py"
        spec = importlib.util.spec_from_file_location("_io_sink", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        null = "NUL" if os.name == "nt" else "/dev/null"
        os.environ["PUBRUN_BENCH_IO_TARGET"] = null
        try:
            assert mod._work() > 0  # write-only sink returns payload size
            os.environ["PUBRUN_BENCH_IO_TARGET"] = str(tmp_path)
            assert mod._work() > 0  # dir target writes + reads back
        finally:
            os.environ.pop("PUBRUN_BENCH_IO_TARGET", None)


# ------------------------------------------------------- IPD: result submission (2026-07-07)

class TestSubmissionVerifier:
    """The redaction verifier gates EVERY transmit path (never publish PII)."""

    def _m(self):
        import pubrun.__main__ as m
        return m

    def test_verifier_passes_redacted(self, tmp_path):
        m = self._m()
        p = tmp_path / "g.redacted.json"
        p.write_text(json.dumps({"schema": "pubrun-benchmark/3",
                                 "machine": {"hostname": "<redacted>"}, "scenarios": []}))
        ok, detail = m._verify_redacted(p)
        assert ok, detail

    def test_verifier_catches_sensitive_key(self, tmp_path):
        m = self._m()
        p = tmp_path / "full.json"
        p.write_text(json.dumps({"machine": {"hostname": "myhost123"}}))
        ok, detail = m._verify_redacted(p)
        assert not ok and "hostname" in detail

    def test_verifier_catches_home_and_username_substring(self, tmp_path):
        m = self._m()
        home = os.path.expanduser("~")
        p = tmp_path / "leak.json"
        # A non-enumerated key still leaks the home dir -> deep substring scan must catch it.
        p.write_text(json.dumps({"scenarios": [{"note": f"ran in {home}/proj"}]}))
        ok, detail = m._verify_redacted(p)
        assert not ok

    def test_verifier_rejects_unparseable(self, tmp_path):
        m = self._m()
        p = tmp_path / "bad.json"
        p.write_text("not json{{{")
        ok, detail = m._verify_redacted(p)
        assert not ok and "JSON" in detail


class TestAttachFlowSubmitFile:
    """Attach flow (IPD 20260721-2255-01): `--submit-file` share-checks a file and shows how
    to ATTACH it; it NEVER transmits the result. A failing share check exits non-zero."""

    def test_submit_file_missing_errors(self):
        res = run_pubrun("bench", "--submit-file", "/nonexistent/x.json")
        assert res.returncode == 1
        assert "no such file" in res.stderr

    def test_submit_file_redacted_shows_attach_block(self, tmp_path):
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"schema": "pubrun-benchmark/5",
                                   "machine": {"host": {"hostname": "<redacted>"}}}))
        res = run_pubrun("bench", "--submit-file", str(red))
        assert res.returncode == 0
        # The unmistakable safe-file block + the Issue Form URL, never a transmit.
        assert "SAFE TO SUBMIT" in res.stderr
        assert "Share check:" in res.stderr and "PASSED" in res.stderr
        assert "issues/new?template=benchmark-result.yml" in res.stderr

    def test_submit_file_unredacted_share_check_fails(self, tmp_path):
        # An unredacted hostname must FAIL the structural share check (non-zero exit).
        full = tmp_path / "full.json"
        full.write_text(json.dumps({"schema": "pubrun-benchmark/5",
                                    "machine": {"host": {"hostname": "realhost-01"}}}))
        res = run_pubrun("bench", "--submit-file", str(full))
        assert res.returncode == 1
        assert "FAILED" in res.stderr

    def test_prepare_submission_copies_only_safe_file(self, tmp_path):
        red = tmp_path / "pubrun-bench-abcd1234-x.redacted.json"
        red.write_text(json.dumps({"schema": "pubrun-benchmark/5",
                                   "machine": {"host": {"hostname": "<redacted>"}}}))
        res = run_pubrun("bench", "--submit-file", str(red), "--prepare-submission")
        assert res.returncode == 0, res.stderr
        share_dir = tmp_path / "pubrun-share"
        assert (share_dir / red.name).is_file()
        # Only the safe file lands in the clean folder.
        assert [p.name for p in share_dir.iterdir()] == [red.name]

    def test_prepare_submission_refuses_unsafe_file(self, tmp_path):
        full = tmp_path / "full.json"
        full.write_text(json.dumps({"schema": "pubrun-benchmark/5",
                                    "machine": {"host": {"hostname": "realhost-01"}}}))
        res = run_pubrun("bench", "--submit-file", str(full), "--prepare-submission")
        assert res.returncode == 1
        assert "Refusing to prepare" in res.stderr
        assert not (tmp_path / "pubrun-share").exists()

    def test_gh_repo_injection_is_literal(self, tmp_path):
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"schema": "pubrun-benchmark/5",
                                   "machine": {"host": {"hostname": "<redacted>"}}}))
        marker = tmp_path / "pwned"
        res = run_pubrun("bench", "--submit-file", str(red),
                         "--gh-repo", f"$(touch {marker})")
        assert res.returncode == 1
        assert "Invalid --gh-repo" in res.stderr
        assert not marker.exists()  # never executed as a shell command


class TestAttachFlowClient:
    """The client prints the safe-file block and stages a clean folder; it never transmits."""

    def _m(self):
        import pubrun.__main__ as m
        return m

    def test_share_check_prefers_structural_validator(self, tmp_path):
        m = self._m()
        # A redacted /5 result passes; an unredacted hostname fails (reason names the field).
        good = tmp_path / "ok.redacted.json"
        good.write_text(json.dumps({"schema": "pubrun-benchmark/5",
                                    "machine": {"host": {"hostname": "<redacted>"}}}))
        ok, reasons = m._share_check(good)
        assert ok and reasons == []
        bad = tmp_path / "bad.json"
        bad.write_text(json.dumps({"machine": {"host": {"hostname": "leaky-host"}}}))
        ok, reasons = m._share_check(bad)
        assert not ok and any("hostname" in r for r in reasons)

    def test_safe_file_block_reports_verdict_and_url(self, tmp_path, capsys):
        m = self._m()
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"schema": "pubrun-benchmark/5",
                                   "machine": {"host": {"hostname": "<redacted>"}}}))
        m._print_safe_file_block(str(tmp_path / "g.unredacted.json"), str(red))
        err = capsys.readouterr().err
        assert "PRIVATE, DO NOT SHARE" in err
        assert "SAFE TO SUBMIT" in err
        assert "PASSED" in err
        assert m._BENCH_SUBMIT_URL in err

    def test_no_auto_post_helpers_remain(self):
        """The paste/auto-post machinery is retired; its symbols must be gone (no leak path)."""
        m = self._m()
        for gone in ("_submit_via_gh", "_submit_via_http", "_submit_benchmark",
                     "_bench_issue_body", "_print_floor", "_resolve_gh_token"):
            assert not hasattr(m, gone), f"{gone} should have been removed (attach flow)"

    def test_submit_url_points_at_main_repo_form(self):
        m = self._m()
        assert "fariello/pubrun/issues/new" in m._BENCH_SUBMIT_URL
        assert "template=benchmark-result.yml" in m._BENCH_SUBMIT_URL
        assert m._DEFAULT_BENCH_REPO == "fariello/pubrun"


class TestSchema5RawTimings:
    """IPD (2026-07-20): compact schema/5 keeps raw per-iteration timings (6 dp) but drops
    the derived stats (recomputable). ``_stats`` is still the shared recompute helper."""

    def test_stats_helper_still_recomputes(self):
        h = _load_harness()
        samples = [0.1, 0.3, 0.2]
        st = h._stats(samples)
        assert st["n"] == 3
        assert st["median_s"] == 0.2  # readers recompute from the retained raw timings

    def test_schema_is_v5(self):
        import re
        src = (_REPO / "benchmarks" / "harness.py").read_text()
        assert re.search(r'"schema":\s*"pubrun-benchmark/5"', src)

    def test_redactor_preserves_timings(self):
        h = _load_harness()
        # schema/5 shape: per-pass timings map keyed by scenario name (numbers survive redaction).
        result = {"machine": {"host": {"hostname": "h"}},
                  "scenario_defs": {"s": {"group": "startup", "mode": "auto",
                                          "workload": "noop.py", "config": {}}},
                  "pass_results": [{"pass": 1, "pass_env": {},
                                    "timings": {"s": [0.1, 0.2, 0.3]},
                                    "failures": {"s": 0}}]}
        red = h.redact_result(result)
        assert red["pass_results"][0]["timings"]["s"] == [0.1, 0.2, 0.3]

    def test_redactor_preserves_environment_kind(self):
        h = _load_harness()
        result = {"machine": {"python": {"environment_kind": "venv", "in_venv": True,
                                         "sys_path_len": 12, "prefix": "/home/bob/venv"}}}
        red = h.redact_result(result)
        py = red["machine"]["python"]
        assert py["environment_kind"] == "venv"  # non-identifying -> survives
        assert py["in_venv"] is True and py["sys_path_len"] == 12
        assert py["prefix"] == "<redacted>"  # the path is still masked


# ------------------------------------------------- IPD-G: benchmark passes (2026-07-07)

class TestBenchTiers:
    """Tier presets, uncaptured baseline pass, and total wall-time (schema/4)."""

    def test_tier_presets(self):
        h = _load_harness()
        assert h._TIERS["quick"] == (15, 2)
        assert h._TIERS["default"] == (30, 3)
        assert h._TIERS["rigorous"] == (50, 5)

    def test_run_records_mode_baseline_and_wall_time(self, tmp_path):
        h = _load_harness()
        out = tmp_path / "b.unredacted.json"
        # tiny run (1 iter, 1 pass) so it's fast; still exercises baseline + wall-time.
        result = h.run(1, out, passes=1, mode="default", baseline_pass=True)
        assert result["mode"] == "default"
        assert result["passes"] == 1 and result["iterations"] == 1
        assert result["baseline_pass"] is True
        assert "total_wall_time_s" in result and result["total_wall_time_s"] >= 0
        # Both timestamps present (schema/5); local carries a UTC offset.
        assert result["generated_utc"].endswith("+00:00")
        assert result["generated_local"][-6] in "+-"
        # Static scenario descriptors are defined ONCE, top-level (no top-level alias).
        assert result["scenario_defs"] and "scenarios" not in result
        # The uncaptured baseline pass is present and separate from measured passes.
        assert "baseline" in result
        assert result["baseline"]["uncaptured"] is True
        assert result["baseline"]["pass"] == 0
        btim = result["baseline"]["timings"]
        assert btim, "baseline pass should have per-scenario timings"
        # Baseline scenarios are the pubrun-absent reference (mode 'baseline' in scenario_defs).
        assert result["scenario_defs"]["baseline-noop"]["mode"] == "baseline"
        assert len(result["pass_results"]) == 1  # 1 measured pass

    def test_no_baseline_flag(self, tmp_path):
        h = _load_harness()
        result = h.run(1, tmp_path / "nb.json", passes=1, baseline_pass=False)
        assert result["baseline_pass"] is False
        assert "baseline" not in result

    def test_aggregate_ignores_baseline_pass(self, tmp_path):
        # aggregate.build_rows reads only top-level "scenarios"; the baseline pass must not
        # break it or leak into the overhead rows.
        h = _load_harness()
        result = h.run(1, tmp_path / "agg.json", passes=1, baseline_pass=True)
        import importlib.util
        ap = _REPO / "benchmarks" / "aggregate.py"
        spec = importlib.util.spec_from_file_location("_bench_aggregate", ap)
        agg = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = agg
        spec.loader.exec_module(agg)
        rows = agg.build_rows([result])  # must not raise
        # No row should reference the baseline PASS (rows are per real scenario only).
        assert all(r.get("scenario") != "baseline" for r in rows)


class TestBenchNoBaselineFlag:
    """IPD (assess-docs D2): `pubrun bench --no-baseline` forwards --no-baseline to the harness."""

    def test_no_baseline_forwarded_to_harness_argv(self, tmp_path, monkeypatch):
        import pubrun.__main__ as m
        import subprocess as sp
        captured = {}

        class _Res:
            returncode = 0

        def _capture(argv, *a, **k):
            captured["argv"] = argv
            return _Res()
        # Local path only (force --local so no scheduler submit); capture the harness argv.
        monkeypatch.setattr(sp, "run", _capture)
        # as_json avoids the interactive contribute path after the (stubbed) run.
        m._run_bench(None, None, False, True, False, False, True, True,
                     no_baseline=True)
        assert "argv" in captured, "harness was not invoked"
        assert "--no-baseline" in captured["argv"]

    def test_no_baseline_absent_by_default(self, tmp_path, monkeypatch):
        import pubrun.__main__ as m
        import subprocess as sp
        captured = {}

        class _Res:
            returncode = 0

        def _capture(argv, *a, **k):
            captured["argv"] = argv
            return _Res()
        monkeypatch.setattr(sp, "run", _capture)
        m._run_bench(None, None, False, True, False, False, True, True,
                     no_baseline=False)
        assert "--no-baseline" not in captured.get("argv", [])
