"""Tests for IPD-C: `pubrun bench` (friendly runner + Slurm submit) and result redaction.

Focus: the SAFETY-critical bits — redaction actually removes PII (deep scan) while keeping
analysis fields, `--no-redact` keeps detail, Slurm is detected but NEVER auto-submitted
without confirmation, and harness resolution fails cleanly for a non-checkout install.
"""
import os
import sys
import json
import getpass
import subprocess
import importlib.util
from pathlib import Path

import pytest

PYTHON = sys.executable
_REPO = Path(__file__).resolve().parents[1]


def _load_harness():
    """Import benchmarks/harness.py directly (it is not on the package path)."""
    path = _REPO / "benchmarks" / "harness.py"
    spec = importlib.util.spec_from_file_location("_bench_harness", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def run_pubrun(*args, cwd=None, env=None, stdin=None, timeout=60):
    e = dict(os.environ)
    if env:
        e.update(env)
    return subprocess.run([PYTHON, "-m", "pubrun"] + list(args), capture_output=True,
                          text=True, cwd=cwd or os.getcwd(), timeout=timeout, env=e, input=stdin)


# --------------------------------------------------------------------------- redaction

class TestRedaction:

    @pytest.fixture
    def sample(self):
        home = os.path.expanduser("~")
        user = getpass.getuser()
        return {
            "machine": {
                "host": {"hostname": "secret-node-01"},
                "python": {
                    "executable": f"{home}/venv/bin/python",
                    "prefix": f"{home}/venv",
                    "sys_path": [f"{home}/project/src", "/usr/lib/python3"],
                },
                "filesystem": {
                    "tmpdir": {"path": "/tmp", "mount_point": "/tmp", "fstype": "tmpfs"},
                    "install": {"path": f"{home}/project", "fstype": "nfs4", "is_network": True},
                },
                "slurm": {"partition": "compute", "node": "cn-9"},
                "hardware": {"cpu": {"model": "Test CPU 9000", "logical_cores": 8}},
            },
            "note": f"generated by {user} under {home}/project",  # un-enumerated PII field
            "pubrun_version": "1.4.0",
        }

    def test_redaction_removes_all_pii(self, sample):
        h = _load_harness()
        red = h.redact_result(sample)
        blob = json.dumps(red)
        assert getpass.getuser() not in blob
        assert os.path.expanduser("~") not in blob
        assert "secret-node-01" not in blob
        assert red["machine"]["host"]["hostname"] == "<redacted>"
        # un-enumerated field scrubbed by the belt-and-suspenders pass
        assert getpass.getuser() not in red["note"]

    def test_redaction_preserves_analysis_fields(self, sample):
        h = _load_harness()
        red = h.redact_result(sample)
        assert red["pubrun_version"] == "1.4.0"
        assert red["machine"]["hardware"]["cpu"]["model"] == "Test CPU 9000"
        assert red["machine"]["hardware"]["cpu"]["logical_cores"] == 8
        assert red["machine"]["slurm"]["partition"] == "compute"
        assert red["machine"]["filesystem"]["tmpdir"]["fstype"] == "tmpfs"
        assert red["machine"]["filesystem"]["install"]["is_network"] is True

    def test_redaction_does_not_mutate_input(self, sample):
        h = _load_harness()
        original = json.dumps(sample)
        h.redact_result(sample)
        assert json.dumps(sample) == original  # deep-copied, input untouched


# ----------------------------------------------------------------- harness resolution

class TestHarnessResolution:

    def test_find_harness_in_checkout(self):
        from pubrun.__main__ import _find_bench_harness
        found = _find_bench_harness()
        assert found is not None
        assert found.name == "harness.py"

    def test_bench_errors_without_checkout(self, tmp_path, monkeypatch):
        """When no harness can be found, bench must error clearly (not crash)."""
        import pubrun.__main__ as m
        monkeypatch.setattr(m, "_find_bench_harness", lambda: None)
        with pytest.raises(SystemExit) as ei:
            m._run_bench(None, None, False, True, False, False, False, False)
        assert ei.value.code == 1


# --------------------------------------------------------------------- Slurm / submit

class TestSlurmSafety:

    def test_slurm_detected_but_not_submitted_without_confirmation(self, monkeypatch, capsys):
        """Slurm present, interactive 'no' answer => must NOT submit."""
        import pubrun.__main__ as m
        monkeypatch.setattr(m, "_slurm_available", lambda: True)
        monkeypatch.setattr(m, "_on_compute_node", lambda: False)
        monkeypatch.setattr("builtins.input", lambda *a: "n")
        called = {"ran": False}
        import subprocess as sp
        def _boom(*a, **k):
            called["ran"] = True
            raise AssertionError("must not submit without confirmation")
        monkeypatch.setattr(sp, "run", _boom)
        # local=False, submit=False, yes=False -> would offer submit, user says no
        m._run_bench(None, None, False, False, False, False, False, False)
        assert called["ran"] is False

    def test_slurm_detection_reads_env(self, monkeypatch):
        from pubrun.__main__ import _slurm_available, _on_compute_node
        monkeypatch.setenv("SLURM_JOB_ID", "12345")
        assert _slurm_available() is True
        assert _on_compute_node() is True
        monkeypatch.delenv("SLURM_JOB_ID", raising=False)


# ------------------------------------------------------------------------- CLI smoke

class TestBenchCLI:

    def test_bench_help(self):
        res = run_pubrun("bench", "--help")
        assert res.returncode == 0
        assert "Examples:" in res.stdout

    def test_bench_quick_local_json(self, tmp_path):
        """A minimal local run writes results + a redacted copy (verified clean).

        Kept as light as possible (1 iteration, 1 pass) but still launches many fresh
        Python subprocesses, so it is a slower end-to-end test (generous timeout).
        """
        res = run_pubrun("bench", "--iterations", "1", "--passes", "1", "--local", "--json",
                         cwd=str(_REPO), timeout=180)
        assert res.returncode == 0, res.stderr
        data = json.loads(res.stdout)
        results = Path(data["results"])
        redacted = Path(data["redacted"])
        try:
            assert results.exists() and redacted.exists()
            blob = redacted.read_text()
            assert getpass.getuser() not in blob
            assert os.path.expanduser("~") not in blob
        finally:
            results.unlink(missing_ok=True)
            redacted.unlink(missing_ok=True)


class TestIoBaselineScenarios:
    """IPD (2026-07-07): /dev/null + /dev/shm + tmpdir ground-truth I/O baselines."""

    def _scenarios(self):
        import importlib.util
        path = _REPO / "benchmarks" / "scenarios.py"
        spec = importlib.util.spec_from_file_location("_bench_scenarios", path)
        mod = importlib.util.module_from_spec(spec)
        # Register before exec so the @dataclass decorator can resolve cls.__module__
        # (Python 3.12+ dataclasses look up sys.modules[cls.__module__] during processing).
        sys.modules[spec.name] = mod
        spec.loader.exec_module(mod)
        return mod.all_scenarios()

    def test_io_baseline_scenarios_registered(self):
        names = {s.name for s in self._scenarios()}
        assert {"io-baseline-devnull", "io-baseline-devshm", "io-baseline-tmpdir"} <= names

    def test_devnull_targets_null_device(self):
        s = next(s for s in self._scenarios() if s.name == "io-baseline-devnull")
        assert s.env.get("PUBRUN_BENCH_IO_TARGET") in ("/dev/null", "NUL")
        assert s.group == "io_baseline"

    def test_devshm_skips_when_unavailable(self):
        s = next(s for s in self._scenarios() if s.name == "io-baseline-devshm")
        reason = s.skip_if() if s.skip_if else None
        # On Linux with /dev/shm writable -> not skipped; elsewhere -> a skip reason string.
        if sys.platform.startswith("linux") and os.path.isdir("/dev/shm") and os.access("/dev/shm", os.W_OK):
            assert reason is None
        else:
            assert isinstance(reason, str) and reason

    def test_io_sink_workload_null_and_tmpdir(self, tmp_path):
        """The io_sink workload handles both a null sink (write-only) and a dir target."""
        import importlib.util
        path = _REPO / "benchmarks" / "workloads" / "io_sink.py"
        spec = importlib.util.spec_from_file_location("_io_sink", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        null = "NUL" if os.name == "nt" else "/dev/null"
        os.environ["PUBRUN_BENCH_IO_TARGET"] = null
        try:
            assert mod._work() > 0  # write-only sink returns payload size
            os.environ["PUBRUN_BENCH_IO_TARGET"] = str(tmp_path)
            assert mod._work() > 0  # dir target writes + reads back
        finally:
            os.environ.pop("PUBRUN_BENCH_IO_TARGET", None)


# ------------------------------------------------------- IPD: result submission (2026-07-07)

class TestSubmissionVerifier:
    """The redaction verifier gates EVERY transmit path (never publish PII)."""

    def _m(self):
        import pubrun.__main__ as m
        return m

    def test_verifier_passes_redacted(self, tmp_path):
        m = self._m()
        p = tmp_path / "g.redacted.json"
        p.write_text(json.dumps({"schema": "pubrun-benchmark/3",
                                 "machine": {"hostname": "<redacted>"}, "scenarios": []}))
        ok, detail = m._verify_redacted(p)
        assert ok, detail

    def test_verifier_catches_sensitive_key(self, tmp_path):
        m = self._m()
        p = tmp_path / "full.json"
        p.write_text(json.dumps({"machine": {"hostname": "myhost123"}}))
        ok, detail = m._verify_redacted(p)
        assert not ok and "hostname" in detail

    def test_verifier_catches_home_and_username_substring(self, tmp_path):
        m = self._m()
        home = os.path.expanduser("~")
        p = tmp_path / "leak.json"
        # A non-enumerated key still leaks the home dir -> deep substring scan must catch it.
        p.write_text(json.dumps({"scenarios": [{"note": f"ran in {home}/proj"}]}))
        ok, detail = m._verify_redacted(p)
        assert not ok

    def test_verifier_rejects_unparseable(self, tmp_path):
        m = self._m()
        p = tmp_path / "bad.json"
        p.write_text("not json{{{")
        ok, detail = m._verify_redacted(p)
        assert not ok and "JSON" in detail


class TestSubmissionConsent:
    """Consent invariant: nothing transmits without an explicit yes in this invocation."""

    def test_submit_file_missing_errors(self):
        res = run_pubrun("bench", "--submit-file", "/nonexistent/x.json")
        assert res.returncode == 1
        assert "no such file" in res.stderr

    def test_submit_file_unredacted_refused(self, tmp_path):
        full = tmp_path / "full.json"
        full.write_text(json.dumps({"machine": {"hostname": "realhost", "username": "bob"}}))
        res = run_pubrun("bench", "--submit-file", str(full))
        assert res.returncode == 1
        assert "Refusing to submit" in res.stderr and "un-redacted" in res.stderr

    def test_submit_file_print_makes_no_network(self, tmp_path, monkeypatch):
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"schema": "pubrun-benchmark/3",
                                   "machine": {"hostname": "<redacted>"}}))
        # --print-submission must never touch the network.
        res = run_pubrun("bench", "--submit-file", str(red), "--print-submission", stdin="")
        assert res.returncode == 0
        assert "Copy-paste submission" in res.stderr
        assert "gh issue create" in res.stderr

    def test_gh_repo_injection_is_literal(self, tmp_path):
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"schema": "pubrun-benchmark/3", "machine": {"hostname": "<redacted>"}}))
        marker = tmp_path / "pwned"
        res = run_pubrun("bench", "--submit-file", str(red),
                         "--gh-repo", f"$(touch {marker})")
        assert res.returncode == 1
        assert "Invalid --gh-repo" in res.stderr
        assert not marker.exists()  # never executed as a shell command


class TestSubmissionChain:
    """The gh -> http -> printed-floor fallback chain, with transport stubbed."""

    def _m(self):
        import pubrun.__main__ as m
        return m

    def test_gh_success_reports_url(self, tmp_path, monkeypatch, capsys):
        m = self._m()
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"machine": {"hostname": "<redacted>"}}))
        monkeypatch.setattr(m, "_submit_via_gh", lambda repo, p: ("https://x/issues/1", None))
        # HTTP must NOT be attempted once gh succeeds.
        monkeypatch.setattr(m, "_submit_via_http", lambda *a, **k: (_ for _ in ()).throw(AssertionError("http should not run")))
        m._submit_benchmark(str(red), "fariello/pubrun-benchmarks", None, None, interactive=False)
        assert "Submitted. Thank you! https://x/issues/1" in capsys.readouterr().err

    def test_gh_unavailable_falls_to_http(self, tmp_path, monkeypatch, capsys):
        m = self._m()
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"machine": {"hostname": "<redacted>"}}))
        monkeypatch.setattr(m, "_submit_via_gh", lambda repo, p: (None, "gh not on PATH"))
        monkeypatch.setattr(m, "_resolve_gh_token", lambda explicit: ("tok", "$GITHUB_TOKEN"))
        monkeypatch.setattr(m, "_submit_via_http", lambda repo, p, t: ("https://x/issues/2", None))
        m._submit_benchmark(str(red), "fariello/pubrun-benchmarks", None, None, interactive=False)
        assert "https://x/issues/2" in capsys.readouterr().err

    def test_all_fail_reaches_floor_with_reasons(self, tmp_path, monkeypatch, capsys):
        m = self._m()
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"machine": {"hostname": "<redacted>"}}))
        monkeypatch.setattr(m, "_submit_via_gh", lambda repo, p: (None, "gh not on PATH"))
        monkeypatch.setattr(m, "_resolve_gh_token", lambda explicit: (None, None))
        m._submit_benchmark(str(red), "fariello/pubrun-benchmarks", None, None, interactive=False)
        err = capsys.readouterr().err
        assert "Automated submission was not possible" in err
        assert "gh not on PATH" in err
        assert "Copy-paste submission" in err  # floor reached (non-interactive -> prints)

    def test_http_error_scrubs_token(self, tmp_path, monkeypatch):
        m = self._m()
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"machine": {"hostname": "<redacted>"}}))
        secret = "ghp_SECRETTOKEN123"

        class _Err(Exception):
            pass

        def boom(req, timeout=None):
            raise _Err(f"boom with {secret}")

        import urllib.request
        monkeypatch.setattr(urllib.request, "urlopen", boom)
        url, reason = m._submit_via_http("o/n", str(red), secret)
        assert url is None
        assert secret not in (reason or "")  # token scrubbed from the error text

    def test_no_token_makes_http_unavailable(self, tmp_path, monkeypatch):
        m = self._m()
        red = tmp_path / "g.redacted.json"
        red.write_text(json.dumps({"machine": {"hostname": "<redacted>"}}))
        # No token -> method reports unavailable BEFORE any urlopen call.
        import urllib.request
        monkeypatch.setattr(urllib.request, "urlopen",
                            lambda *a, **k: (_ for _ in ()).throw(AssertionError("must not POST")))
        url, reason = m._submit_via_http("o/n", str(red), None)
        assert url is None and "token" in (reason or "")


class TestSchema4RawTimings:
    """IPD data-quality (2026-07-07): raw per-iteration timings + schema /4."""

    def test_stats_and_timings_coexist(self):
        h = _load_harness()
        samples = [0.1, 0.3, 0.2]
        entry = {"failures": 0, "timings": list(samples), **h._stats(samples)}
        assert entry["timings"] == samples  # raw, in run order (not sorted)
        assert entry["n"] == 3
        assert entry["median_s"] == 0.2  # summary still derivable & present

    def test_schema_is_v4(self):
        import re
        src = (_REPO / "benchmarks" / "harness.py").read_text()
        assert re.search(r'"schema":\s*"pubrun-benchmark/4"', src)

    def test_redactor_preserves_timings(self):
        h = _load_harness()
        result = {"machine": {"host": {"hostname": "h"}},
                  "pass_results": [{"pass": 1, "scenarios": {
                      "s": {"timings": [0.1, 0.2, 0.3], "median_s": 0.2, "n": 3}}}]}
        red = h.redact_result(result)
        got = red["pass_results"][0]["scenarios"]["s"]
        assert got["timings"] == [0.1, 0.2, 0.3]  # numbers survive redaction

    def test_redactor_preserves_environment_kind(self):
        h = _load_harness()
        result = {"machine": {"python": {"environment_kind": "venv", "in_venv": True,
                                         "sys_path_len": 12, "prefix": "/home/bob/venv"}}}
        red = h.redact_result(result)
        py = red["machine"]["python"]
        assert py["environment_kind"] == "venv"  # non-identifying -> survives
        assert py["in_venv"] is True and py["sys_path_len"] == 12
        assert py["prefix"] == "<redacted>"  # the path is still masked
