import argparse
import sys
import os
import json
import importlib.resources
import tempfile
import subprocess
from pathlib import Path


def _create_config(destination: str) -> None:
    try:
        resource_path = importlib.resources.files("runtrace").joinpath("resources", "default.toml")
        content = resource_path.read_text(encoding="utf-8")
        
        target_path = Path(destination).resolve()
        if target_path.exists():
            print(f"Error: '{target_path}' already exists. Refusing to overwrite.", file=sys.stderr)
            sys.exit(1)
            
        target_path.write_text(content, encoding="utf-8")
        print(f"[OK] Successfully created configuration at: {target_path}")
        
    except Exception as e:
        print(f"Failed to create config: {e}", file=sys.stderr)
        sys.exit(1)


def _show_info() -> None:
    from runtrace.capture.hardware import get_hardware
    from runtrace.capture.invocation import get_invocation
    
    print("==================================================")
    print("          runtrace Hardware Diagnostics           ")
    print("==================================================\n")
    
    print("--- [ Invocation Details ] ---")
    data = {"invocation": get_invocation(), "hardware": get_hardware({})}
    print(json.dumps(data, indent=2))
    print("\nIf GPU logs are missing here, your active Python environment")
    print("may not have permission to query `nvidia-smi` or NVML natively.")


def _run_tests() -> None:
    print("==================================================")
    print("        runtrace Pipeline Evaluation Mode         ")
    print("==================================================\n")
    
    # 1. Run Tox/PyTest if we are inside the source repository
    if Path("tests").exists() and Path("tox.ini").exists():
        print("[*] Source repository detected. Running PyTest matrix...")
        try:
            subprocess.run(["python", "-m", "pytest", "tests/", "-q"])
        except Exception:
            print("[WARN] PyTest execution failed.")
    
    # 2. Run Integrated Diagnostic Mock Script
    print("\n[*] Executing Native End-to-End Mock Script...")
    MOCK_SCRIPT = """
import time
import os
import runtrace

print('Starting Mock Training Environment...')

# Fake some ML workload
tracker = runtrace.start()
runtrace.annotate('initializing_model', layers=3, opt='adam')
time.sleep(0.6)

with runtrace.phase('epoch_1'):
    print('Epoch 1: loss = 0.95')
    # Trigger an internal subprocess to evaluate monkey-patch depth
    os.system('echo "Evaluating internal shell capture hooks..."')
    time.sleep(0.4)

with runtrace.phase('epoch_2'):
    print('Epoch 2: loss = 0.45')
    time.sleep(0.4)

print('Mock Training Complete.')
"""
    with tempfile.TemporaryDirectory() as td:
        script_path = Path(td) / "mock_training.py"
        script_path.write_text(MOCK_SCRIPT.strip(), encoding="utf-8")
        
        env = os.environ.copy()
        env["RUNTRACE_AUTO_START"] = "true"
        
        # Execute it
        result = subprocess.run([sys.executable, str(script_path)], env=env, capture_output=True, text=True, cwd=td)
        
        if result.returncode != 0:
            print(f"[FAIL] Mock Evaluation Failed. Exit Code: {result.returncode}")
            print(f"STDERR:\n{result.stderr}")
            return
            
        print("[OK] Mock Script Executed Natively without crashing.")
        
        # Validate output directory
        runs_dir = Path(td) / "runs"
        if not runs_dir.exists():
            print("[FAIL] runs/ directory was not generated by runtrace.")
            return
            
        run_folders = list(runs_dir.iterdir())
        if not run_folders:
            print("[FAIL] No active tracking artifact dir generated.")
            return
            
        active_run = run_folders[0]
        manifest_p = active_run / "manifest.json"
        
        if not manifest_p.exists():
            print("[FAIL] manifest.json was not successfully serialized.")
            return
            
        try:
            manifest_data = json.loads(manifest_p.read_text(encoding="utf-8"))
            rcs = manifest_data.get("subprocesses", [])
            print(f"[OK] Subprocess Monkeypatch captured {len(rcs)} internal shell commands seamlessly.")
            print(f"[OK] Architecture Validated. Tracking context generated efficiently.")
        except Exception as e:
            print(f"[FAIL] Failure parsing generated manifest: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(description="runtrace context capture utility.")
    
    parser.add_argument(
        "--create-config",
        type=str,
        nargs="?",
        const=".runtrace.toml",
        metavar="DEST",
        help="Create a default runtrace.toml. Defaults to current directory if no path is provided."
    )
    
    parser.add_argument(
        "--info",
        action="store_true",
        help="Diagnostics: Prints the host capabilities and execution context."
    )
    
    parser.add_argument(
        "--run-tests",
        action="store_true",
        help="Diagnostics: Executes a mock ML payload locally to evaluate trace capture viability."
    )
    
    args = parser.parse_args()

    executed = False

    if args.create_config:
        _create_config(args.create_config)
        executed = True
        
    if args.info:
        _show_info()
        executed = True
        
    if args.run_tests:
        _run_tests()
        executed = True

    if not executed:
        parser.print_help()


if __name__ == "__main__":
    main()
